services:
  postgres:
    images: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD","pg_isready","-U",'airflow']
      interval: 5s
      retries: 5
    restart: always

# posgresql
docker run -it \
	-e POSTGRES_USER="root" \
  -e POSTGRES_PASSWORD="root" \
  -e POSTGRES_DB="ny_taxi" \
  -v /Users/atufashireen/projects/DE_ZoomCamp/week1/ny_data:/var/lib/postgresql/data\
  -p 5432:5432 \
	postgres:13

#pgadmin
docker run -it \
-e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
-e PGADMIN_DEFAULT_PASSWORD="root" \
-p 8081:80 \
dpage/pgadmin4


#network (pgsql+pgadmin)
#pgsql
docker run -it \
-e POSTGRES_USER="root" \
-e POSTGRES_PASSWORD="root" \
-e POSTGRES_DB="ny_taxi" \
-v /Users/atufashireen/projects/DE_ZoomCamp/week1/ny_data:/var/lib/postgresql/data \
-p 5432:5432 \
--network=pg-network \
--name pg-database \
postgres:13

#pgadmin
docker run -it \
-e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
-e PGADMIN_DEFAULT_PASSWORD="root" \
-p 8080:80 \
--network=pg-network \
--name pg-admin \
dpage/pgadmin4


URL="https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.parquet"
python ingest_data.py \
--user=root \
--password=root \
--host=localhost \
--port=5432 \
--db=ny_taxi \
--table_name=yellow_taxt_trip \
--url=https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.parquet


docker build -t taxi_ingest:v001 .

docker run -it \
--network=pg-network \
taxi_ingest:v001 \
--user=root \
--password=root \
--host=pg-database \
--port=5432 \
--db=ny_taxi \
--table_name=yellow_taxt_trip \
--url=http://103.228.33.188:8000/:8000/datasets/yellow_tripdata_2021-01.parquet
